mongo {
  uri = "mongodb://admin:admin123@localhost:27017"
  database = "taskdb"
  collection = "tasks"
}

# Persistence type
# Possible values: "inmemory" (default) or "mongo"
repository.type = "mongo"
